from sqlalchemy import String, Integer, Boolean, DateTime, ForeignKey, Float, Text, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from datetime import datetime
from typing import List, Optional
from app.database.database import Base

class Website(Base):
    __tablename__ = "websites"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    domain: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    robots_checked: Mapped[bool] = mapped_column(Boolean, default=False)
    crawl_delay: Mapped[int] = mapped_column(Integer, default=0)

    # Relationships
    pages: Mapped[List["Page"]] = relationship("Page", back_populates="website", cascade="all, delete-orphan")


class Page(Base):
    __tablename__ = "pages"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    url: Mapped[str] = mapped_column(Text, unique=True, nullable=False, index=True)
    title: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    content: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    html: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    status_code: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    crawl_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    language: Mapped[Optional[str]] = mapped_column(String(10), nullable=True)
    page_hash: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    website_id: Mapped[int] = mapped_column(Integer, ForeignKey("websites.id", ondelete="CASCADE"), nullable=False)

    # Incremental crawl fields (HTTP conditional request caching)
    etag: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)         # ETag response header
    last_modified: Mapped[Optional[str]] = mapped_column(String(100), nullable=True) # Last-Modified response header
    last_checked: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)  # Last time we verified freshness

    # PageRank score — updated by PageRankCalculator on demand
    pagerank: Mapped[float] = mapped_column(Float, default=0.15, nullable=False, index=True)

    # Relationships
    website: Mapped["Website"] = relationship("Website", back_populates="pages")
    inverted_index_entries: Mapped[List["InvertedIndex"]] = relationship("InvertedIndex", back_populates="page", cascade="all, delete-orphan")
    embedding: Mapped[Optional["PageEmbedding"]] = relationship("PageEmbedding", back_populates="page", cascade="all, delete-orphan", uselist=False)


class Link(Base):
    __tablename__ = "links"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    source_page: Mapped[int] = mapped_column(Integer, ForeignKey("pages.id", ondelete="CASCADE"), nullable=False, index=True)
    destination_page: Mapped[int] = mapped_column(Integer, ForeignKey("pages.id", ondelete="CASCADE"), nullable=False, index=True)

    __table_args__ = (
        UniqueConstraint("source_page", "destination_page", name="uq_source_destination"),
    )


class PageEmbedding(Base):
    """
    Stores the semantic embedding vector for a page, generated by
    EmbeddingEngine (sentence-transformers all-MiniLM-L6-v2).
    Stored as JSON-encoded float list for portability.
    """
    __tablename__ = "page_embeddings"

    page_id: Mapped[int] = mapped_column(Integer, ForeignKey("pages.id", ondelete="CASCADE"), primary_key=True)
    embedding: Mapped[str] = mapped_column(Text, nullable=False)   # JSON-encoded list[float]
    model_name: Mapped[str] = mapped_column(String(100), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    page: Mapped["Page"] = relationship("Page", back_populates="embedding")


class QueueItem(Base):
    __tablename__ = "queue"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    url: Mapped[str] = mapped_column(Text, unique=True, nullable=False, index=True)
    status: Mapped[str] = mapped_column(String(20), default="pending", index=True)  # pending, crawling, completed, failed
    depth: Mapped[int] = mapped_column(Integer, default=0)
    priority: Mapped[int] = mapped_column(Integer, default=0)
    retry_count: Mapped[int] = mapped_column(Integer, default=0)


class SearchHistory(Base):
    __tablename__ = "search_history"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    query: Mapped[str] = mapped_column(Text, nullable=False)
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class Word(Base):
    __tablename__ = "words"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    word: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)

    # Relationships
    index_entries: Mapped[List["InvertedIndex"]] = relationship("InvertedIndex", back_populates="word", cascade="all, delete-orphan")


class InvertedIndex(Base):
    __tablename__ = "inverted_index"

    word_id: Mapped[int] = mapped_column(Integer, ForeignKey("words.id", ondelete="CASCADE"), primary_key=True)
    page_id: Mapped[int] = mapped_column(Integer, ForeignKey("pages.id", ondelete="CASCADE"), primary_key=True)
    tf: Mapped[float] = mapped_column(Float, nullable=False)  # Term Frequency in this document

    # Relationships
    word: Mapped["Word"] = relationship("Word", back_populates="index_entries")
    page: Mapped["Page"] = relationship("Page", back_populates="inverted_index_entries")
